import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { RunResult, ReviewResult, ValidationResult, Issue } from "./schemas/review.js";
import type { GatingResult } from "./gating.js";

interface ReportData {
  result: RunResult;
  gating?: GatingResult;
}

export async function loadReportData(runDir: string): Promise<ReportData> {
  const resultRaw = await readFile(join(runDir, "result.json"), "utf-8");
  const result: RunResult = JSON.parse(resultRaw);

  let gating: GatingResult | undefined;
  try {
    const gatingRaw = await readFile(join(runDir, "gating.json"), "utf-8");
    gating = JSON.parse(gatingRaw);
  } catch {
    // gating.json may not exist for review-skipped runs
  }

  return { result, gating };
}

export function generateReport(data: ReportData): string {
  const { result, gating } = data;
  const { review, validation } = result;

  const duration = getDuration(result.started_at, result.completed_at);
  const passed = result.exit_code === 0;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>patchy-pilot report — ${esc(result.run_id)}</title>
<style>
${CSS}
</style>
</head>
<body>
<div class="container">

<header>
  <div class="logo">patchy-pilot</div>
  <div class="run-id">${esc(result.run_id)}</div>
</header>

<section class="hero ${passed ? "hero-pass" : "hero-fail"}">
  <div class="hero-badge">${passed ? "PASSED" : "FAILED"}</div>
  <div class="hero-meta">
    <span>Exit code ${result.exit_code}</span>
    <span>${esc(duration)}</span>
    <span>Builder: ${esc(result.builder_provider)}</span>
    <span>Reviewer: ${esc(result.reviewer_provider)}</span>
    ${result.repair_applied ? '<span class="tag tag-repair">Repair applied</span>' : ""}
  </div>
</section>

<section class="spec">
  <h2>Spec</h2>
  <pre>${esc(result.spec)}</pre>
</section>

${renderValidation(validation)}

${review ? renderReview(review) : '<section><h2>Review</h2><p class="muted">Review was skipped.</p></section>'}

${gating ? renderGating(gating) : ""}

${review ? renderSummary(review) : ""}

<footer>
  Generated by patchy-pilot on ${new Date().toISOString().slice(0, 19).replace("T", " ")} UTC
</footer>

</div>
</body>
</html>`;
}

function renderValidation(v: ValidationResult): string {
  const checks = (["formatter", "linter", "typecheck", "tests"] as const)
    .filter((k) => v[k])
    .map((k) => {
      const c = v[k]!;
      return `<div class="check ${c.passed ? "check-pass" : "check-fail"}">
  <span class="check-icon">${c.passed ? "&#10003;" : "&#10007;"}</span>
  <span class="check-name">${k}</span>
  ${c.output ? `<details><summary>output</summary><pre>${esc(c.output)}</pre></details>` : ""}
</div>`;
    });

  if (checks.length === 0) {
    return `<section><h2>Validation</h2><p class="muted">No validation checks configured.</p></section>`;
  }

  return `<section>
  <h2>Validation ${v.all_passed ? '<span class="badge badge-pass">all passed</span>' : '<span class="badge badge-fail">failures</span>'}</h2>
  <div class="checks">${checks.join("\n")}</div>
</section>`;
}

function renderReview(r: ReviewResult): string {
  const categories: { key: keyof ReviewResult; label: string }[] = [
    { key: "critical_issues", label: "Critical Issues" },
    { key: "likely_bugs", label: "Likely Bugs" },
    { key: "missing_tests", label: "Missing Tests" },
    { key: "spec_mismatches", label: "Spec Mismatches" },
    { key: "risky_changes", label: "Risky Changes" },
    { key: "hidden_assumptions", label: "Hidden Assumptions" },
  ];

  const sections = categories
    .map(({ key, label }) => {
      const issues = r[key] as Issue[];
      if (issues.length === 0) return "";
      return `<div class="issue-group">
  <h3>${label} <span class="count">${issues.length}</span></h3>
  ${issues.map(renderIssue).join("\n")}
</div>`;
    })
    .filter(Boolean);

  const recClass = recommendationClass(r.merge_recommendation);

  return `<section>
  <h2>Review</h2>
  <div class="review-header">
    <div class="metric">
      <span class="metric-value">${r.confidence.toFixed(2)}</span>
      <span class="metric-label">Confidence</span>
    </div>
    <div class="metric">
      <span class="metric-value rec ${recClass}">${formatRecommendation(r.merge_recommendation)}</span>
      <span class="metric-label">Recommendation</span>
    </div>
  </div>
  ${sections.length > 0 ? sections.join("\n") : '<p class="muted">No issues found.</p>'}
</section>`;
}

function renderIssue(issue: Issue): string {
  const sevClass = `sev-${issue.severity}`;
  const location = issue.file
    ? `<span class="issue-location">${esc(issue.file)}${issue.line ? `:${issue.line}` : ""}</span>`
    : "";
  const suggestion = issue.suggestion
    ? `<div class="issue-suggestion"><strong>Suggestion:</strong> ${esc(issue.suggestion)}</div>`
    : "";

  return `<div class="issue">
  <div class="issue-header">
    <span class="sev ${sevClass}">${issue.severity}</span>
    ${location}
  </div>
  <div class="issue-desc">${esc(issue.description)}</div>
  ${suggestion}
</div>`;
}

function renderGating(g: GatingResult): string {
  return `<section>
  <h2>Gating ${g.passed ? '<span class="badge badge-pass">passed</span>' : '<span class="badge badge-fail">failed</span>'}</h2>
  ${
    g.reasons.length > 0
      ? `<ul class="reasons">${g.reasons.map((r) => `<li>${esc(r)}</li>`).join("\n")}</ul>`
      : '<p class="muted">All thresholds met.</p>'
  }
</section>`;
}

function renderSummary(r: ReviewResult): string {
  return `<section class="summary">
  <h2>Summary</h2>
  <p>${esc(r.short_summary)}</p>
</section>`;
}

function formatRecommendation(rec: string): string {
  return rec.replace(/_/g, " ");
}

function recommendationClass(rec: string): string {
  switch (rec) {
    case "safe_to_merge":
      return "rec-safe";
    case "merge_with_minor_fixes":
      return "rec-minor";
    case "needs_changes":
      return "rec-changes";
    case "do_not_merge":
      return "rec-block";
    default:
      return "";
  }
}

function getDuration(start: string, end: string): string {
  const ms = new Date(end).getTime() - new Date(start).getTime();
  const secs = Math.floor(ms / 1000);
  if (secs < 60) return `${secs}s`;
  const mins = Math.floor(secs / 60);
  const remSecs = secs % 60;
  return `${mins}m ${remSecs}s`;
}

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const CSS = `
:root {
  --bg: #0d1117;
  --surface: #161b22;
  --border: #30363d;
  --text: #e6edf3;
  --text-muted: #8b949e;
  --accent: #58a6ff;
  --green: #3fb950;
  --red: #f85149;
  --yellow: #d29922;
  --orange: #db6d28;
  --purple: #bc8cff;
}

* { margin: 0; padding: 0; box-sizing: border-box; }

body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
}

.container {
  max-width: 900px;
  margin: 0 auto;
  padding: 2rem 1.5rem;
}

header {
  display: flex;
  justify-content: space-between;
  align-items: baseline;
  margin-bottom: 1.5rem;
}

.logo {
  font-size: 1.1rem;
  font-weight: 700;
  color: var(--accent);
  letter-spacing: -0.02em;
}

.run-id {
  font-family: "SF Mono", "Fira Code", monospace;
  font-size: 0.85rem;
  color: var(--text-muted);
}

/* Hero */
.hero {
  border-radius: 8px;
  padding: 1.5rem;
  margin-bottom: 2rem;
  border: 1px solid var(--border);
}
.hero-pass { border-color: var(--green); background: #0d1117e6; }
.hero-fail { border-color: var(--red); background: #1a0a0ae6; }

.hero-badge {
  font-size: 1.5rem;
  font-weight: 800;
  letter-spacing: 0.05em;
  margin-bottom: 0.5rem;
}
.hero-pass .hero-badge { color: var(--green); }
.hero-fail .hero-badge { color: var(--red); }

.hero-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
  font-size: 0.85rem;
  color: var(--text-muted);
}

.tag { padding: 0.15em 0.5em; border-radius: 4px; font-size: 0.8rem; }
.tag-repair { background: var(--purple); color: #fff; }

/* Sections */
section {
  margin-bottom: 2rem;
}

h2 {
  font-size: 1.15rem;
  margin-bottom: 0.75rem;
  padding-bottom: 0.4rem;
  border-bottom: 1px solid var(--border);
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

h3 {
  font-size: 0.95rem;
  margin-bottom: 0.5rem;
  color: var(--text-muted);
}

.count {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 0 0.5em;
  font-size: 0.8rem;
}

.badge {
  font-size: 0.75rem;
  padding: 0.15em 0.6em;
  border-radius: 4px;
  font-weight: 600;
  text-transform: uppercase;
}
.badge-pass { background: var(--green); color: #000; }
.badge-fail { background: var(--red); color: #fff; }

.muted { color: var(--text-muted); font-style: italic; }

/* Spec */
.spec pre {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 1rem;
  font-size: 0.85rem;
  white-space: pre-wrap;
  word-break: break-word;
  max-height: 300px;
  overflow-y: auto;
}

/* Validation checks */
.checks {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  gap: 0.75rem;
}

.check {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 0.75rem;
}
.check-pass { border-left: 3px solid var(--green); }
.check-fail { border-left: 3px solid var(--red); }

.check-icon { margin-right: 0.4rem; }
.check-pass .check-icon { color: var(--green); }
.check-fail .check-icon { color: var(--red); }

.check-name {
  font-weight: 600;
  text-transform: capitalize;
}

.check details { margin-top: 0.5rem; }
.check summary {
  font-size: 0.8rem;
  color: var(--text-muted);
  cursor: pointer;
}
.check pre {
  margin-top: 0.3rem;
  font-size: 0.75rem;
  background: var(--bg);
  padding: 0.5rem;
  border-radius: 4px;
  white-space: pre-wrap;
  word-break: break-word;
  max-height: 200px;
  overflow-y: auto;
}

/* Review header metrics */
.review-header {
  display: flex;
  gap: 2rem;
  margin-bottom: 1.5rem;
}

.metric {
  display: flex;
  flex-direction: column;
}

.metric-value {
  font-size: 1.5rem;
  font-weight: 700;
}

.metric-label {
  font-size: 0.8rem;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.rec { text-transform: capitalize; }
.rec-safe { color: var(--green); }
.rec-minor { color: var(--yellow); }
.rec-changes { color: var(--orange); }
.rec-block { color: var(--red); }

/* Issues */
.issue-group {
  margin-bottom: 1.5rem;
}

.issue {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 0.75rem 1rem;
  margin-bottom: 0.5rem;
}

.issue-header {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-bottom: 0.4rem;
}

.sev {
  font-size: 0.7rem;
  font-weight: 700;
  text-transform: uppercase;
  padding: 0.1em 0.5em;
  border-radius: 3px;
}
.sev-critical { background: var(--red); color: #fff; }
.sev-high { background: var(--orange); color: #fff; }
.sev-medium { background: var(--yellow); color: #000; }
.sev-low { background: var(--border); color: var(--text); }
.sev-info { background: var(--accent); color: #000; }

.issue-location {
  font-family: "SF Mono", "Fira Code", monospace;
  font-size: 0.8rem;
  color: var(--accent);
}

.issue-desc {
  font-size: 0.85rem;
  line-height: 1.5;
}

.issue-suggestion {
  margin-top: 0.4rem;
  font-size: 0.8rem;
  color: var(--text-muted);
  padding-left: 0.5rem;
  border-left: 2px solid var(--border);
}

/* Gating */
.reasons {
  list-style: none;
  padding: 0;
}
.reasons li {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 4px;
  padding: 0.5rem 0.75rem;
  margin-bottom: 0.4rem;
  font-size: 0.85rem;
}
.reasons li::before {
  content: "\\2022";
  color: var(--red);
  margin-right: 0.5rem;
}

/* Summary */
.summary p {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 1rem;
  font-size: 0.9rem;
  line-height: 1.7;
}

footer {
  text-align: center;
  font-size: 0.75rem;
  color: var(--text-muted);
  padding-top: 2rem;
  border-top: 1px solid var(--border);
}
`;
