import type { RunSummary, TrendStats } from "./history.js";

export function generateTrendsReport(runs: RunSummary[], stats: TrendStats): string {
  // Chronological order for charts (oldest → newest)
  const chron = [...runs].reverse();

  const confidenceValues = chron
    .filter((r) => r.confidence !== undefined)
    .map((r) => r.confidence!);

  const issueValues = chron.map((r) => r.total_issues);
  const criticalValues = chron.map((r) => r.critical_issues);

  const trendArrow =
    stats.confidence_trend === "improving"
      ? "↑"
      : stats.confidence_trend === "declining"
        ? "↓"
        : "→";

  const trendColor =
    stats.confidence_trend === "improving"
      ? "#3fb950"
      : stats.confidence_trend === "declining"
        ? "#f85149"
        : "#d29922";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>patchy-pilot — Trends</title>
<style>
${CSS}
</style>
</head>
<body>
<div class="container">

<header>
  <div class="logo">patchy-pilot</div>
  <div class="subtitle">Review Trends</div>
</header>

<section class="stats-grid">
  <div class="stat-card">
    <div class="stat-value">${stats.total_runs}</div>
    <div class="stat-label">Total Runs</div>
  </div>
  <div class="stat-card">
    <div class="stat-value ${stats.pass_rate >= 0.7 ? "text-green" : stats.pass_rate >= 0.4 ? "text-yellow" : "text-red"}">${pct(stats.pass_rate)}</div>
    <div class="stat-label">Pass Rate</div>
  </div>
  <div class="stat-card">
    <div class="stat-value">${stats.avg_confidence.toFixed(2)}</div>
    <div class="stat-label">Avg Confidence</div>
  </div>
  <div class="stat-card">
    <div class="stat-value" style="color: ${trendColor}">${trendArrow} ${stats.confidence_trend}</div>
    <div class="stat-label">Confidence Trend</div>
  </div>
  <div class="stat-card">
    <div class="stat-value ${stats.validation_pass_rate >= 0.8 ? "text-green" : "text-yellow"}">${pct(stats.validation_pass_rate)}</div>
    <div class="stat-label">Validation Pass Rate</div>
  </div>
</section>

${
  confidenceValues.length >= 2
    ? `<section>
  <h2>Confidence Over Time</h2>
  <div class="chart-wrap">
    ${svgLineChart(confidenceValues, 0, 1, "#58a6ff", chron.filter((r) => r.confidence !== undefined).map((r) => r.run_id))}
  </div>
</section>`
    : ""
}

${
  chron.length >= 2
    ? `<section>
  <h2>Issue Counts Over Time</h2>
  <div class="chart-wrap">
    ${svgMultiLineChart(
      [
        { values: issueValues, color: "#d29922", label: "Total" },
        { values: criticalValues, color: "#f85149", label: "Critical" },
      ],
      chron.map((r) => r.run_id),
    )}
  </div>
  <div class="legend">
    <span class="legend-item"><span class="legend-dot" style="background:#d29922"></span>Total issues</span>
    <span class="legend-item"><span class="legend-dot" style="background:#f85149"></span>Critical issues</span>
  </div>
</section>`
    : ""
}

${renderRecommendationDistribution(stats.recommendation_distribution, stats.total_runs)}

<section>
  <h2>Run History</h2>
  ${renderRunTable(runs)}
</section>

<footer>
  Generated by patchy-pilot on ${new Date().toISOString().slice(0, 19).replace("T", " ")} UTC
</footer>

</div>
</body>
</html>`;
}

function svgLineChart(
  values: number[],
  yMin: number,
  yMax: number,
  color: string,
  labels: string[],
): string {
  const W = 720;
  const H = 180;
  const pad = { top: 12, right: 12, bottom: 24, left: 36 };
  const innerW = W - pad.left - pad.right;
  const innerH = H - pad.top - pad.bottom;
  const range = yMax - yMin || 1;

  const pts = values.map((v, i) => {
    const x = pad.left + (values.length === 1 ? innerW / 2 : (i / (values.length - 1)) * innerW);
    const y = pad.top + innerH - ((v - yMin) / range) * innerH;
    return { x, y, v, label: labels[i] ?? "" };
  });

  const polyline = pts.map((p) => `${p.x},${p.y}`).join(" ");

  const gridLines = [0, 0.25, 0.5, 0.75, 1].map((t) => {
    const v = yMin + t * range;
    const y = pad.top + innerH - t * innerH;
    return `<line x1="${pad.left}" y1="${y}" x2="${W - pad.right}" y2="${y}" stroke="#30363d" stroke-width="1"/>
<text x="${pad.left - 4}" y="${y + 4}" text-anchor="end" fill="#8b949e" font-size="10">${v.toFixed(2)}</text>`;
  });

  const circles = pts.map(
    (p) =>
      `<circle cx="${p.x}" cy="${p.y}" r="4" fill="${color}" stroke="#0d1117" stroke-width="1.5">
  <title>${p.label}: ${p.v.toFixed(2)}</title>
</circle>`,
  );

  return `<svg width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" style="max-width:100%">
  ${gridLines.join("\n")}
  <polyline points="${polyline}" fill="none" stroke="${color}" stroke-width="2.5" stroke-linejoin="round"/>
  ${circles.join("\n")}
</svg>`;
}

function svgMultiLineChart(
  series: { values: number[]; color: string; label: string }[],
  labels: string[],
): string {
  const W = 720;
  const H = 180;
  const pad = { top: 12, right: 12, bottom: 24, left: 36 };
  const innerW = W - pad.left - pad.right;
  const innerH = H - pad.top - pad.bottom;

  const allVals = series.flatMap((s) => s.values);
  const yMin = 0;
  const yMax = Math.max(...allVals, 1);
  const range = yMax - yMin || 1;
  const n = labels.length;

  const toX = (i: number) =>
    pad.left + (n === 1 ? innerW / 2 : (i / (n - 1)) * innerW);
  const toY = (v: number) =>
    pad.top + innerH - ((v - yMin) / range) * innerH;

  const gridLines = Array.from({ length: 5 }, (_, k) => {
    const t = k / 4;
    const v = yMin + t * range;
    const y = pad.top + innerH - t * innerH;
    return `<line x1="${pad.left}" y1="${y}" x2="${W - pad.right}" y2="${y}" stroke="#30363d" stroke-width="1"/>
<text x="${pad.left - 4}" y="${y + 4}" text-anchor="end" fill="#8b949e" font-size="10">${Math.round(v)}</text>`;
  });

  const renderedSeries = series.map((s) => {
    const pts = s.values.map((v, i) => `${toX(i)},${toY(v)}`).join(" ");
    const circles = s.values.map(
      (v, i) =>
        `<circle cx="${toX(i)}" cy="${toY(v)}" r="3.5" fill="${s.color}" stroke="#0d1117" stroke-width="1.5">
  <title>${labels[i]}: ${s.label} = ${v}</title>
</circle>`,
    );
    return `<polyline points="${pts}" fill="none" stroke="${s.color}" stroke-width="2" stroke-linejoin="round"/>
${circles.join("\n")}`;
  });

  return `<svg width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" style="max-width:100%">
  ${gridLines.join("\n")}
  ${renderedSeries.join("\n")}
</svg>`;
}

function renderRecommendationDistribution(dist: Record<string, number>, total: number): string {
  if (Object.keys(dist).length === 0) return "";

  const order = ["safe_to_merge", "merge_with_minor_fixes", "needs_changes", "do_not_merge"];
  const colors: Record<string, string> = {
    safe_to_merge: "#3fb950",
    merge_with_minor_fixes: "#d29922",
    needs_changes: "#db6d28",
    do_not_merge: "#f85149",
  };

  const bars = order
    .filter((k) => dist[k])
    .map((k) => {
      const count = dist[k] ?? 0;
      const pctVal = count / total;
      const widthPct = Math.round(pctVal * 100);
      return `<div class="dist-row">
  <div class="dist-label">${k.replace(/_/g, " ")}</div>
  <div class="dist-bar-wrap">
    <div class="dist-bar" style="width:${widthPct}%;background:${colors[k] ?? "#8b949e"}"></div>
  </div>
  <div class="dist-count">${count} <span class="muted">(${pct(pctVal)})</span></div>
</div>`;
    });

  return `<section>
  <h2>Merge Recommendation Distribution</h2>
  <div class="dist">${bars.join("\n")}</div>
</section>`;
}

function renderRunTable(runs: RunSummary[]): string {
  if (runs.length === 0) return '<p class="muted">No runs found.</p>';

  const rows = runs.map((r) => {
    const recClass =
      r.merge_recommendation === "safe_to_merge"
        ? "rec-safe"
        : r.merge_recommendation === "merge_with_minor_fixes"
          ? "rec-minor"
          : r.merge_recommendation === "needs_changes"
            ? "rec-changes"
            : r.merge_recommendation === "do_not_merge"
              ? "rec-block"
              : "";

    const dateStr = r.started_at.slice(0, 10);
    const passed = r.exit_code === 0;

    return `<tr>
  <td class="mono">${esc(r.run_id)}</td>
  <td>${dateStr}</td>
  <td>${r.confidence !== undefined ? r.confidence.toFixed(2) : "—"}</td>
  <td class="${r.critical_issues > 0 ? "text-red" : ""}">${r.critical_issues}</td>
  <td>${r.total_issues}</td>
  <td class="${recClass}">${r.merge_recommendation ? r.merge_recommendation.replace(/_/g, " ") : "—"}</td>
  <td>${r.validation_passed ? '<span class="text-green">✓</span>' : '<span class="text-red">✗</span>'}</td>
  <td class="${passed ? "text-green" : "text-red"}">${passed ? "PASS" : "FAIL"}</td>
  <td class="spec-cell muted">${esc(r.spec_preview)}${r.spec_preview.length >= 60 ? "…" : ""}</td>
</tr>`;
  });

  return `<div class="table-wrap">
<table>
  <thead>
    <tr>
      <th>Run ID</th>
      <th>Date</th>
      <th>Conf</th>
      <th>Crit</th>
      <th>Issues</th>
      <th>Recommendation</th>
      <th>Valid</th>
      <th>Gate</th>
      <th>Spec</th>
    </tr>
  </thead>
  <tbody>
    ${rows.join("\n")}
  </tbody>
</table>
</div>`;
}

function pct(n: number): string {
  return `${Math.round(n * 100)}%`;
}

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const CSS = `
:root {
  --bg: #0d1117;
  --surface: #161b22;
  --border: #30363d;
  --text: #e6edf3;
  --text-muted: #8b949e;
  --accent: #58a6ff;
  --green: #3fb950;
  --red: #f85149;
  --yellow: #d29922;
  --orange: #db6d28;
}

* { margin: 0; padding: 0; box-sizing: border-box; }

body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
}

.container {
  max-width: 960px;
  margin: 0 auto;
  padding: 2rem 1.5rem;
}

header {
  display: flex;
  justify-content: space-between;
  align-items: baseline;
  margin-bottom: 1.5rem;
}

.logo {
  font-size: 1.1rem;
  font-weight: 700;
  color: var(--accent);
  letter-spacing: -0.02em;
}

.subtitle {
  font-size: 0.9rem;
  color: var(--text-muted);
}

/* Stats grid */
.stats-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
  gap: 1rem;
  margin-bottom: 2rem;
}

.stat-card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1rem;
  text-align: center;
}

.stat-value {
  font-size: 1.6rem;
  font-weight: 700;
  margin-bottom: 0.25rem;
}

.stat-label {
  font-size: 0.75rem;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.text-green { color: var(--green); }
.text-yellow { color: var(--yellow); }
.text-red { color: var(--red); }

/* Sections */
section {
  margin-bottom: 2.5rem;
}

h2 {
  font-size: 1.1rem;
  margin-bottom: 1rem;
  padding-bottom: 0.4rem;
  border-bottom: 1px solid var(--border);
}

.muted { color: var(--text-muted); }

/* Charts */
.chart-wrap {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1rem;
  overflow-x: auto;
}

/* Legend */
.legend {
  display: flex;
  gap: 1.5rem;
  margin-top: 0.75rem;
  font-size: 0.8rem;
  color: var(--text-muted);
}

.legend-item {
  display: flex;
  align-items: center;
  gap: 0.4rem;
}

.legend-dot {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  flex-shrink: 0;
}

/* Distribution bars */
.dist {
  display: flex;
  flex-direction: column;
  gap: 0.6rem;
}

.dist-row {
  display: grid;
  grid-template-columns: 200px 1fr 80px;
  align-items: center;
  gap: 0.75rem;
  font-size: 0.85rem;
}

.dist-label {
  text-transform: capitalize;
  color: var(--text-muted);
}

.dist-bar-wrap {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 4px;
  height: 16px;
  overflow: hidden;
}

.dist-bar {
  height: 100%;
  min-width: 4px;
  border-radius: 3px;
  transition: width 0.3s;
}

.dist-count {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

/* Table */
.table-wrap {
  overflow-x: auto;
}

table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.8rem;
}

th, td {
  padding: 0.5rem 0.75rem;
  text-align: left;
  border-bottom: 1px solid var(--border);
}

th {
  color: var(--text-muted);
  text-transform: uppercase;
  font-size: 0.7rem;
  letter-spacing: 0.05em;
  font-weight: 600;
}

tr:hover td {
  background: var(--surface);
}

.mono {
  font-family: "SF Mono", "Fira Code", monospace;
  font-size: 0.75rem;
}

.spec-cell {
  max-width: 280px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-size: 0.75rem;
}

.rec-safe { color: var(--green); }
.rec-minor { color: var(--yellow); }
.rec-changes { color: var(--orange); }
.rec-block { color: var(--red); }

footer {
  text-align: center;
  font-size: 0.75rem;
  color: var(--text-muted);
  padding-top: 2rem;
  border-top: 1px solid var(--border);
}
`;
